name: Build and publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - uses: typst-community/setup-typst@v4

      - name: Build
        run: just build-all

      - name: Debug
        run: echo "Updating release ${{ github.ref_name }}"

      - name: Update release
        run: gh release upload ${{ github.ref_name }} cv_en.pdf cv_ru.pdf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
