name: Build and publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - uses: typst-community/setup-typst@v4

      - name: Build
        run: just build-all

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cv_en.pdf
            cv_ru.pdf
          name: "Release ${{ github.ref_name }}"
          body: "Compiled pdfs of CV rev. ${{ github.ref_name }}."
          draft: false
          prerelease: false
